title: SuiteT
description: A Theme Generator for SugarCRM, SuiteCRM
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

github:
  zip_url: https://github.com/blasher/SuiteT/zipball/master
  tar_url: https://github.com/blasher/SuiteT/tarball/master

gems:
  - jekyll-mentions
